server:
  port: 18080
  servlet:
    context-path: /manager
spring:
  profiles:
    active: dev
  application:
    name: user-service-manager
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

mybatis:
  mapper-locations: classpath*:/mapper*/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
