spring:
  profiles:
    active: dev
  application:
    name: user-service-client
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath*:/mapper*/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true